name: Auto Deploy Self-Hosted Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Sync to  homelab
        run: |
          mkdir -p ~/homelab/apps/portfolio
          rsync -av --delete ./ ~/homelab/apps/portfolio

      - name: Deploy containers
        run: |
          cd ~/homelab
          docker compose down
          docker compose up -d --build